# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'
  pod 'Google-Maps-iOS-Utils', '6.1.0'
  pod 'GoogleMaps', '9.3.0'
  pod 'sqlite3', '3.49.0'

end
